//! Autocomplétion shell : `apabot completions bash|zsh|fish`.
//!
//! Les scripts sont GÉNÉRÉS à partir de la liste réelle des sous-commandes
//! ([`crate::ops::SUBCOMMANDS`]) : impossible qu'ils dérivent quand une
//! commande apparaît ou disparaît. Les options par sous-commande restent
//! statiques (elles changent rarement) et sont couvertes par les tests.

use crate::i18n::Catalog;

/// Sous-commandes proposées à l'autocomplétion : celles de l'usage, plus
/// `completions` ; `supervise` est interne (lancé par `start`) et masqué.
pub const USER_SUBCOMMANDS: [&str; 15] = [
    "run",
    "start",
    "stop",
    "restart",
    "status",
    "logs",
    "mission-control",
    "monitor",
    "systemd",
    "help",
    "install",
    "reinstall",
    "uninstall",
    "config",
    "completions",
];

/// Script d'autocomplétion pour un shell, `None` si inconnu.
pub fn script_for(shell: &str) -> Option<String> {
    match shell {
        "bash" => Some(bash_script()),
        "zsh" => Some(zsh_script()),
        "fish" => Some(fish_script()),
        _ => None,
    }
}

/// `apabot completions <shell>` : imprime le script sur stdout (à sourcer
/// ou à écrire dans le dossier de complétion du shell).
pub fn cmd_completions(args: &[String], catalog: &Catalog) -> i32 {
    let shell = args.get(2).map(String::as_str).unwrap_or("");
    match script_for(shell) {
        Some(script) => {
            print!("{script}");
            0
        }
        None => {
            eprintln!("{}", catalog.ops.completions_usage);
            2
        }
    }
}

fn bash_script() -> String {
    const TPL: &str = r#"# bash completion for apabot — generated by `apabot completions bash`
_apabot_completion() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    local subcommands="{SUBCOMMANDS}"
    local global_opts="--help -h --lang --non-interactive"

    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$subcommands $global_opts" -- "$cur") )
        return 0
    fi

    case "$prev" in
        --env-file) COMPREPLY=( $(compgen -f -- "$cur") ); return 0 ;;
        --lines)    COMPREPLY=( $(compgen -W "10 20 50 100" -- "$cur") ); return 0 ;;
        --lang)     COMPREPLY=( $(compgen -W "fr en" -- "$cur") ); return 0 ;;
    esac

    case "${COMP_WORDS[1]}" in
        logs)
            COMPREPLY=( $(compgen -W "--lines --no-follow" -- "$cur") ) ;;
        systemd)
            if [[ "$prev" == "systemd" ]]; then
                COMPREPLY=( $(compgen -W "install remove" -- "$cur") )
            else
                COMPREPLY=( $(compgen -W "--dry-run" -- "$cur") )
            fi ;;
        install|reinstall)
            COMPREPLY=( $(compgen -W "--dry-run --refresh-assets --env-file --name" -- "$cur") ) ;;
        uninstall)
            COMPREPLY=( $(compgen -W "--dry-run --name" -- "$cur") ) ;;
        config)
            COMPREPLY=( $(compgen -W "edit save load list delete" -- "$cur") ) ;;
        completions)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ) ;;
        *)
            COMPREPLY=( $(compgen -W "$global_opts" -- "$cur") ) ;;
    esac
    return 0
}
complete -F _apabot_completion apabot
"#;
    TPL.replace("{SUBCOMMANDS}", &USER_SUBCOMMANDS.join(" "))
}

fn zsh_script() -> String {
    const TPL: &str = r#"#compdef apabot
# zsh completion for apabot — generated by `apabot completions zsh`
_apabot() {
    if (( CURRENT == 2 )); then
        _values 'command' {SUBCOMMANDS}
        return
    fi
    case "$words[2]" in
        logs)
            _arguments '--lines[number of lines]:lines:' '--no-follow[do not follow]' ;;
        systemd)
            if (( CURRENT == 3 )); then
                _values 'action' install remove
            else
                _values 'option' '--dry-run[show the plan only]'
            fi ;;
        install|reinstall)
            _arguments '--dry-run[show the plan only]' '--refresh-assets[rewrite the card GIFs]' '--env-file[path to a .env]:file:_files' '--name[instance name]:name:' ;;
        uninstall)
            _arguments '--dry-run[show the plan only]' '--name[instance name]:name:' ;;
        config)
            _values 'action' edit save load list delete ;;
        completions)
            _values 'shell' bash zsh fish ;;
        *)
            _arguments '--help[show usage]' '--lang[language]:lang:(fr en)' '--non-interactive[no prompts]' ;;
    esac
}
compdef _apabot apabot
"#;
    TPL.replace("{SUBCOMMANDS}", &USER_SUBCOMMANDS.join(" "))
}

fn fish_script() -> String {
    let mut out = String::from(
        "# fish completion for apabot — generated by `apabot completions fish`\n",
    );
    for sub in USER_SUBCOMMANDS {
        out.push_str(&format!("complete -c apabot -n '__fish_use_subcommand' -a {sub}\n"));
    }
    out.push_str("complete -c apabot -l help -s h -d 'Show usage'\n");
    out.push_str("complete -c apabot -l lang -r -a 'fr en'\n");
    out.push_str("complete -c apabot -l non-interactive -d 'No prompts'\n");
    out.push_str("complete -c apabot -n '__fish_seen_subcommand_from logs' -l lines -r\n");
    out.push_str("complete -c apabot -n '__fish_seen_subcommand_from logs' -l no-follow\n");
    out.push_str("complete -c apabot -n '__fish_seen_subcommand_from systemd' -a 'install remove'\n");
    out.push_str("complete -c apabot -n '__fish_seen_subcommand_from systemd' -l dry-run\n");
    out.push_str(
        "complete -c apabot -n '__fish_seen_subcommand_from install reinstall' -l dry-run -l refresh-assets -l env-file -r -l name -r\n",
    );
    out.push_str("complete -c apabot -n '__fish_seen_subcommand_from uninstall' -l dry-run -l name -r\n");
    out.push_str("complete -c apabot -n '__fish_seen_subcommand_from config' -a 'edit save load list delete'\n");
    out.push_str("complete -c apabot -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish'\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_subcommands_match_the_real_cli() {
        // Chaque sous-commande proposée existe réellement dans l'aiguillage
        // (ou est la nouvelle commande `completions`) — sinon le script
        // compléterait des commandes inconnues.
        for sub in USER_SUBCOMMANDS {
            assert!(
                crate::ops::SUBCOMMANDS.contains(&sub) || sub == "completions",
                "{sub} n'est pas une sous-commande réelle"
            );
        }
        // La commande interne du superviseur reste masquée.
        assert!(!USER_SUBCOMMANDS.contains(&"supervise"));
    }

    #[test]
    fn every_script_lists_every_subcommand() {
        for shell in ["bash", "zsh", "fish"] {
            let script = script_for(shell).expect("shell connu");
            for sub in USER_SUBCOMMANDS {
                assert!(
                    script.contains(sub),
                    "le script {shell} ne mentionne pas `{sub}`"
                );
            }
        }
    }

    #[test]
    fn scripts_cover_the_install_flags() {
        for shell in ["bash", "zsh", "fish"] {
            let script = script_for(shell).expect("shell connu");
            // bash/zsh : `--refresh-assets` ; fish : `-l refresh-assets` —
            // on vérifie le token commun.
            assert!(
                script.contains("refresh-assets"),
                "le script {shell} ne propose pas --refresh-assets"
            );
            assert!(
                script.contains("env-file"),
                "le script {shell} ne propose pas --env-file"
            );
        }
    }

    #[test]
    fn unknown_shell_has_no_script() {
        assert!(script_for("powershell").is_none());
        assert!(script_for("").is_none());
    }
}
